spring:
  datasource:
    url: jdbc:sqlserver://VG;databaseName=DGEmpres81
    username: sa
    password: calderon
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      validationTimeout:
        jpa: 300000
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        use_nationalized_character_data: true
jwt:
  secret: secret
  expiration: 45000